name: PsychoPy-timings
channels:
  - cogsci
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - mamba
  - pip:
    - ipykernel
    - ipyfilechooser
    - ipympl
    - ipywidgets
    - jupyter
    - mne
    - numpy==1.26.4
    - pandas
    - psychtoolbox
    - psychopy
    - psychopy-sounddevice
    - pyserial
