name: PsychoPy-timings
channels:
  - cogsci
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - mamba
  - pip:
    - numpy==1.26.4
    - psychtoolbox
    - psychopy
    - psychopy-sounddevice
    - pyserial
